### PR TITLE
Add account-nonce command

### PR DESCRIPTION
**Pull request by mvandeberg**
## Brief description

Adds an account_nonce command that mirrors the account_rc command.

## Checklist

- [X] I have built this pull request locally
- [ ] I have ran the unit tests locally
- [X] I have manually tested this pull request
- [X] I have reviewed my pull request
- [ ] I have added any relevant tests

### CODE REVIEW

**Review by sgerbino — CHANGES_REQUESTED** [review]

**Comment by sgerbino** [comment]
There is a nonce command already that shows the next nonce... is this just adding duplicate functionality?

https://github.com/koinos/koinos-cli/blob/be6ee2d00ba3bb21c8a3927eb4a436865c0016a4/internal/cli/commands.go#L833

**Comment by mvandeberg** [comment]
The `nonce` command is designed to set the nonce for the open wallet. It is like the `rc_limit` command, which sets the rc limit for the open wallet. The `nonce` command can only be run on the open wallet.

Note the defined arguments of the command:

https://github.com/koinos/koinos-cli/blob/be6ee2d00ba3bb21c8a3927eb4a436865c0016a4/internal/cli/commands.go#L110

The only argument is the nonce.

The added command will show the nonce of the open wallet (which does duplicate the behavior of the `nonce` command when set to `auto`), but is also accepts an address and will return the nonce of that address.

Adding this command follows the pattern of the `rc_limit` and `account_rc` commands.

**Comment by mvandeberg** [comment]
This work was done several weeks ago when I was working on the offline signing exchange documentation and I kept forgetting to push the changes and make a PR. I needed this functionality to do offline signing completely within the CLI. It also solves a pain point of mine for the last several months where I have to query a nonce from the API and decode the returned Protobuf message using an online tool. The workflow was acceptable for me because I understand all of the steps, but is not acceptable to ask an exchange to do those steps, nor is it easily automated. This command allows automation of the process using just the CLI.

**Review by sgerbino — APPROVED** [review]

**Review by sgerbino — CHANGES_REQUESTED** [review]
The command is called `AccountNonce` and says that it "cannot get account nonce" but what you actually return is the next account nonce. This seems confusing to me.

I would say that it either should be called `NextAccountNonce` or it should just return the current account nonce? I would lean toward the latter just in case the nonce pattern changes...

**Review by sgerbino — APPROVED** [review]

**Pull request merged**
